version: '3.1'

services:
  backend:
    container_name: backend
    restart: always
    build: ./back
    ports:
      - "8084:8084"
    depends_on:
      - mongo-db

  frontend:
    container_name: frontend
    restart: always
    build: ./front
    ports:
      - "3000:3000"

  mongo-db:
    image: "mongo"
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-client:
    image: "mongo-express"
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo-db:27017/
    depends_on:
      - mongo-db
